[package]
name = "vulkan-helper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = "0.37.2"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.3.5", features = ["derive"] }
libc = "0.2.147"

[profile.release]
lto = true
strip = true
